- hosts: webservers
  roles:
    - user_environment
  vars:
    index_content: "This is server {{ansible_hostname}}!"
    root_dir: /usr/share/nginx/html
    nginx_port: 80
    username: "desired_username"
    password: "desired_password"
    users: 
      - jaime
      - sansa
      - robert
  tasks:
    - name: update APT cache
      ansible.builtin.apt: 
        update_cache: yes
      become: yes

    - name: install Make
      ansible.builtin.apt: 
        name: make 
        state: present 
        update_cache: yes
      become: yes
      tags: make

    - name: create users
      ansible.builtin.user:
       name: "{{item}}"
      become: yes
      with_items: "{{users}}"
      tags: user

    - name: Create SSH directory for each user
      ansible.builtin.file:
        path: "/home/{{ item }}/.ssh"
        state: directory
        owner: "{{item}}"
        group: "{{item}}"
      become: yes
      with_items: "{{users}}"
      tags: git

    - name: Copy Git configuration file
      ansible.builtin.template:
        src: files/gitconfig
        dest: "/home/{{ item }}/.gitconfig"
        owner: "{{item}}"
        group: "{{item}}"
      become: yes
      with_items: "{{users}}"
      tags: git

    - name: Upload public SSH key
      ansible.builtin.copy:
        src: files/id_rsa.pub
        dest: "/home/{{ item }}/.ssh/authorized_keys"
        owner: "{{ item }}"
        group: "{{ item }}"
        mode: "0600"
      become: yes
      with_items: "{{ users }}"
      tags: git

    - name: install cowsay
      ansible.builtin.apt: 
        name: cowsay 
        state: present 
        update_cache: yes
      become: yes
      tags: [nginx, cowsay]

    - name: Register Cowsay output
      ansible.builtin.command:
        cmd: "cowsay 'This is server {{ ansible_hostname }}!'"
      register: cowsay_result
      tags: [cowsay, nginx]
    
    - name: install nginx
      ansible.builtin.apt: 
        name: nginx 
        state: present 
        update_cache: yes
      become: yes
      tags: nginx

    - name: Copy HTML file
      ansible.builtin.template:
        src: files/index.html.j2
        dest: "{{root_dir}}/index.html"
      become: yes
      tags: nginx

    - name: Copy Nginx configuration file
      ansible.builtin.template:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: restart nginx
      become: yes
      tags: nginx
    
  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes

      