- hosts: webservers
  vars:
    root_dir: /usr/share/nginx/html
    nginx_port: 80
  tasks:
    - name: update APT cache
      ansible.builtin.apt: 
        update_cache: yes
      become: yes

    - name: install git
      ansible.builtin.apt: 
        name: git 
        state: present 
        update_cache: yes
      become: yes
      tags: git

    - name: install Make
      ansible.builtin.apt: 
        name: make 
        state: present 
        update_cache: yes
      become: yes
      tags: make
      
    - name: install nodejs
      ansible.builtin.apt: 
        name: nodejs 
        state: present 
        update_cache: yes
      become: yes
      tags: nodejs

    - name: remove git
      ansible.builtin.apt:
       name: git
       state: absent
      become: yes
      tags: git

    - name: add user arya
      ansible.builtin.user:
       name: arya
      become: yes
      tags: user
    
    - name: add user sansa
      ansible.builtin.user:
       name: sansa
      become: yes
      tags: user

    - name: add user tirion
      ansible.builtin.user:
       name: tirion
      become: yes
      tags: user

    - name: install nginx
      ansible.builtin.apt: 
        name: nginx 
        state: present 
        update_cache: yes
      become: yes
      tags: nginx

    - name: Copy HTML file
      ansible.builtin.copy:
        src: files/index.html
        dest: "{{root_dir}}/index.html"
      become: yes
      tags: nginx

    - name: Copy Nginx configuration file
      ansible.builtin.template:
        src: files/nginx.conf
        dest: /etc/nginx/nginx.conf
      notify: restart nginx
      become: yes
      tags: nginx
    
  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes

      